#!/bin/sh
set -e

CONFIG_FILE="/data/config.yaml"
MEDIAMTX_CONFIG="/mediamtx.yml"

echo "FeedView Relay starting..."

# Create default config if not exists
if [ ! -f "$CONFIG_FILE" ]; then
    echo "Creating default configuration..."
    cat > "$CONFIG_FILE" << 'EOF'
# FeedView Relay Configuration
# Add your camera RTSP URLs here

cameras:
  # Example camera configuration:
  # camera1:
  #   name: "Front Door"
  #   rtsp_url: "rtsp://admin:password@192.168.1.100:554/cam/realmonitor?channel=1&subtype=1"
  #   enabled: true
  #
  # camera2:
  #   name: "Backyard"
  #   rtsp_url: "rtsp://admin:password@192.168.1.100:554/cam/realmonitor?channel=2&subtype=1"
  #   enabled: true

  demo:
    name: "Demo Stream (Big Buck Bunny)"
    rtsp_url: "rtsp://localhost:8554/demo"
    enabled: true
    is_demo: true
EOF
fi

# Parse config and generate MediaMTX paths
echo "Generating MediaMTX configuration..."

cat > "$MEDIAMTX_CONFIG" << 'EOF'
# MediaMTX Configuration - Auto-generated by FeedView Relay

logLevel: info
logDestinations: [stdout]

# API for health checks
api: yes
apiAddress: :9997

# RTSP server (for local testing)
rtsp: yes
rtspAddress: :8554

# HLS output (browser-compatible)
hls: yes
hlsAddress: :8888
hlsAlwaysRemux: yes
hlsVariant: lowLatency
hlsSegmentCount: 3
hlsSegmentDuration: 1s
hlsPartDuration: 200ms
hlsSegmentMaxSize: 50M
hlsAllowOrigin: '*'

# WebRTC (optional, lower latency)
webrtc: yes
webrtcAddress: :8889

# Health check endpoint
paths:
  healthcheck:
    source: publisher

  # Demo stream using Big Buck Bunny
  demo:
    source: rtsp://localhost:8554/demo_internal
    sourceOnDemand: yes

  demo_internal:
    runOnInit: ffmpeg -re -stream_loop -1 -i https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8 -c copy -f rtsp rtsp://localhost:8554/demo_internal
    runOnInitRestart: yes

EOF

# Read cameras from config and add to MediaMTX paths
if command -v yq > /dev/null 2>&1; then
    # If yq is available, parse YAML properly
    echo "  # Camera streams from FeedView Relay config" >> "$MEDIAMTX_CONFIG"
    
    # This is a simplified parser - in production use yq or similar
    grep -E "^\s+\w+:" "$CONFIG_FILE" 2>/dev/null | while read -r line; do
        camera_id=$(echo "$line" | sed 's/://g' | tr -d ' ')
        if [ "$camera_id" != "cameras" ] && [ "$camera_id" != "demo" ]; then
            # Get the RTSP URL for this camera (simplified parsing)
            rtsp_url=$(grep -A5 "^  $camera_id:" "$CONFIG_FILE" | grep "rtsp_url:" | sed 's/.*rtsp_url: *"\(.*\)"/\1/' | tr -d '"')
            enabled=$(grep -A5 "^  $camera_id:" "$CONFIG_FILE" | grep "enabled:" | grep -c "true" || echo "0")
            
            if [ -n "$rtsp_url" ] && [ "$enabled" = "1" ]; then
                echo "" >> "$MEDIAMTX_CONFIG"
                echo "  $camera_id:" >> "$MEDIAMTX_CONFIG"
                echo "    source: $rtsp_url" >> "$MEDIAMTX_CONFIG"
                echo "    sourceOnDemand: yes" >> "$MEDIAMTX_CONFIG"
                echo "Added camera: $camera_id"
            fi
        fi
    done
else
    echo "Note: yq not available, using demo stream only"
fi

echo ""
echo "========================================="
echo "FeedView Relay is starting!"
echo "========================================="
echo ""
echo "Your HLS streams will be available at:"
echo "  http://[your-start9]:8888/demo"
echo ""
echo "To add cameras, edit the config in StartOS UI"
echo "or modify /data/config.yaml"
echo ""
echo "========================================="
echo ""

# Start MediaMTX
exec /mediamtx "$MEDIAMTX_CONFIG"
