// FeedView Relay - Set Configuration Script
// Saves configuration from StartOS UI

import { types as T, compat } from "../deps.ts";

export const setConfig: T.ExpectedExports.setConfig = async (effects, input) => {
  const config = input as {
    cameras: Array<{
      id: string;
      name: string;
      rtsp_url: string;
      enabled: boolean;
    }>;
    demo_stream: boolean;
  };

  // Build the config.yaml content
  let configYaml = `# FeedView Relay Configuration
# Auto-generated by StartOS

cameras:
`;

  // Add demo stream if enabled
  if (config.demo_stream) {
    configYaml += `  demo:
    name: "Demo Stream (Big Buck Bunny)"
    rtsp_url: "rtsp://localhost:8554/demo"
    enabled: true
    is_demo: true

`;
  }

  // Add user-configured cameras
  for (const camera of config.cameras) {
    if (camera.id && camera.rtsp_url) {
      configYaml += `  ${camera.id}:
    name: "${camera.name}"
    rtsp_url: "${camera.rtsp_url}"
    enabled: ${camera.enabled}

`;
    }
  }

  // Write config file
  await effects.writeFile({
    volumeId: "main",
    path: "config.yaml",
    toWrite: configYaml
  });

  return {
    signal: "SIGTERM",
    "depends-on": {}
  };
};
